# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_fit_python_sdk import schemas  # noqa: F401


class CollaboratorContracts(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    The list of contracts of the collaborator. Only available if `collaborators:contracts:read` scope is set on the token.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['CollaboratorContractsItem']:
            return CollaboratorContractsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['CollaboratorContractsItem'], typing.List['CollaboratorContractsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'CollaboratorContracts':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'CollaboratorContractsItem':
        return super().__getitem__(i)

from pay_fit_python_sdk.model.collaborator_contracts_item import CollaboratorContractsItem
