# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_fit_python_sdk import schemas  # noqa: F401


class GetCollaboratorsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "collaborators",
        }
        
        class properties:
        
            @staticmethod
            def collaborators() -> typing.Type['GetCollaboratorsResponseCollaborators']:
                return GetCollaboratorsResponseCollaborators
        
            @staticmethod
            def meta() -> typing.Type['GetCollaboratorsResponseMeta']:
                return GetCollaboratorsResponseMeta
            __annotations__ = {
                "collaborators": collaborators,
                "meta": meta,
            }
    
    collaborators: 'GetCollaboratorsResponseCollaborators'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["collaborators"]) -> 'GetCollaboratorsResponseCollaborators': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meta"]) -> 'GetCollaboratorsResponseMeta': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["collaborators", "meta", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["collaborators"]) -> 'GetCollaboratorsResponseCollaborators': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meta"]) -> typing.Union['GetCollaboratorsResponseMeta', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["collaborators", "meta", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        collaborators: 'GetCollaboratorsResponseCollaborators',
        meta: typing.Union['GetCollaboratorsResponseMeta', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GetCollaboratorsResponse':
        return super().__new__(
            cls,
            *args,
            collaborators=collaborators,
            meta=meta,
            _configuration=_configuration,
            **kwargs,
        )

from pay_fit_python_sdk.model.get_collaborators_response_collaborators import GetCollaboratorsResponseCollaborators
from pay_fit_python_sdk.model.get_collaborators_response_meta import GetCollaboratorsResponseMeta
