# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from pay_fit_python_sdk import PayFit

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        payfit = PayFit(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(payfit)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
