# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from pay_fit_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from pay_fit_python_sdk.api_response import AsyncGeneratorResponse
from pay_fit_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_fit_python_sdk import schemas  # noqa: F401

from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation_request import ContractUpdateProvidentFundAffiliationRequest as ContractUpdateProvidentFundAffiliationRequestSchema
from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation400_response import ContractUpdateProvidentFundAffiliation400Response as ContractUpdateProvidentFundAffiliation400ResponseSchema
from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation_request_provident_fund_contract_ids import ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds as ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIdsSchema
from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation403_response import ContractUpdateProvidentFundAffiliation403Response as ContractUpdateProvidentFundAffiliation403ResponseSchema
from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation404_response import ContractUpdateProvidentFundAffiliation404Response as ContractUpdateProvidentFundAffiliation404ResponseSchema
from pay_fit_python_sdk.model.contract_update_provident_fund_affiliation401_response import ContractUpdateProvidentFundAffiliation401Response as ContractUpdateProvidentFundAffiliation401ResponseSchema

from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation404_response import ContractUpdateProvidentFundAffiliation404Response
from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation400_response import ContractUpdateProvidentFundAffiliation400Response
from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation403_response import ContractUpdateProvidentFundAffiliation403Response
from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation401_response import ContractUpdateProvidentFundAffiliation401Response
from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation_request_provident_fund_contract_ids import ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds
from pay_fit_python_sdk.type.contract_update_provident_fund_affiliation_request import ContractUpdateProvidentFundAffiliationRequest

from ...api_client import Dictionary
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation400_response import ContractUpdateProvidentFundAffiliation400Response as ContractUpdateProvidentFundAffiliation400ResponsePydantic
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation_request_provident_fund_contract_ids import ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds as ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIdsPydantic
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation403_response import ContractUpdateProvidentFundAffiliation403Response as ContractUpdateProvidentFundAffiliation403ResponsePydantic
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation401_response import ContractUpdateProvidentFundAffiliation401Response as ContractUpdateProvidentFundAffiliation401ResponsePydantic
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation404_response import ContractUpdateProvidentFundAffiliation404Response as ContractUpdateProvidentFundAffiliation404ResponsePydantic
from pay_fit_python_sdk.pydantic.contract_update_provident_fund_affiliation_request import ContractUpdateProvidentFundAffiliationRequest as ContractUpdateProvidentFundAffiliationRequestPydantic

# Path params
CompanyIdSchema = schemas.StrSchema
ContractIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyId': typing.Union[CompanyIdSchema, str, ],
        'contractId': typing.Union[ContractIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_id = api_client.PathParameter(
    name="companyId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyIdSchema,
    required=True,
)
request_path_contract_id = api_client.PathParameter(
    name="contractId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ContractIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = ContractUpdateProvidentFundAffiliationRequestSchema


request_body_contract_update_provident_fund_affiliation_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor204ResponseBodyApplicationJson = schemas.DictSchema


@dataclass
class ApiResponseFor204(api_client.ApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


@dataclass
class ApiResponseFor204Async(api_client.AsyncApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


_response_for_204 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor204,
    response_cls_async=ApiResponseFor204Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor204ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ContractUpdateProvidentFundAffiliation400ResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ContractUpdateProvidentFundAffiliation400Response


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ContractUpdateProvidentFundAffiliation400Response


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = ContractUpdateProvidentFundAffiliation401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: ContractUpdateProvidentFundAffiliation401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: ContractUpdateProvidentFundAffiliation401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = ContractUpdateProvidentFundAffiliation403ResponseSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: ContractUpdateProvidentFundAffiliation403Response


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: ContractUpdateProvidentFundAffiliation403Response


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = ContractUpdateProvidentFundAffiliation404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: ContractUpdateProvidentFundAffiliation404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: ContractUpdateProvidentFundAffiliation404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_provident_fund_affiliation_mapped_args(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if provident_fund_contract_ids is not None:
            _body["providentFundContractIds"] = provident_fund_contract_ids
        args.body = _body
        if company_id is not None:
            _path_params["companyId"] = company_id
        if contract_id is not None:
            _path_params["contractId"] = contract_id
        args.path = _path_params
        return args

    async def _aupdate_provident_fund_affiliation_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Update a Provident Fund of an employee&#x27;s contract
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
            request_path_contract_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/contracts-fr/{contractId}/provident-fund',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_contract_update_provident_fund_affiliation_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_provident_fund_affiliation_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Update a Provident Fund of an employee&#x27;s contract
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
            request_path_contract_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/contracts-fr/{contractId}/provident-fund',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_contract_update_provident_fund_affiliation_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdateProvidentFundAffiliationRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_provident_fund_affiliation(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_provident_fund_affiliation_mapped_args(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
        )
        return await self._aupdate_provident_fund_affiliation_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def update_provident_fund_affiliation(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
    ) -> typing.Union[
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_provident_fund_affiliation_mapped_args(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
        )
        return self._update_provident_fund_affiliation_oapg(
            body=args.body,
            path_params=args.path,
        )

class UpdateProvidentFundAffiliation(BaseApi):

    async def aupdate_provident_fund_affiliation(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
        validate: bool = False,
        **kwargs,
    ) -> Dictionary:
        raw_response = await self.raw.aupdate_provident_fund_affiliation(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
            **kwargs,
        )
        if validate:
            return Dictionary(**raw_response.body)
        return api_client.construct_model_instance(Dictionary, raw_response.body)
    
    
    def update_provident_fund_affiliation(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
        validate: bool = False,
    ) -> Dictionary:
        raw_response = self.raw.update_provident_fund_affiliation(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
        )
        if validate:
            return Dictionary(**raw_response.body)
        return api_client.construct_model_instance(Dictionary, raw_response.body)


class ApiForput(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aput(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_provident_fund_affiliation_mapped_args(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
        )
        return await self._aupdate_provident_fund_affiliation_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def put(
        self,
        provident_fund_contract_ids: ContractUpdateProvidentFundAffiliationRequestProvidentFundContractIds,
        company_id: str,
        contract_id: str,
    ) -> typing.Union[
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_provident_fund_affiliation_mapped_args(
            provident_fund_contract_ids=provident_fund_contract_ids,
            company_id=company_id,
            contract_id=contract_id,
        )
        return self._update_provident_fund_affiliation_oapg(
            body=args.body,
            path_params=args.path,
        )

