# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.get_collaborators401_response import GetCollaborators401Response
from pay_fit_python_sdk import configuration


class TestGetCollaborators401Response(unittest.TestCase):
    """GetCollaborators401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
