# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.get_health_insurance_contracts404_response import GetHealthInsuranceContracts404Response
from pay_fit_python_sdk import configuration


class TestGetHealthInsuranceContracts404Response(unittest.TestCase):
    """GetHealthInsuranceContracts404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
