# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.contract_list_worked_time_by_pay_period404_response import ContractListWorkedTimeByPayPeriod404Response
from pay_fit_python_sdk import configuration


class TestContractListWorkedTimeByPayPeriod404Response(unittest.TestCase):
    """ContractListWorkedTimeByPayPeriod404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
