# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.contract_get_french_info400_response import ContractGetFrenchInfo400Response
from pay_fit_python_sdk import configuration


class TestContractGetFrenchInfo400Response(unittest.TestCase):
    """ContractGetFrenchInfo400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
