# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.get_company_accounting_v2_response import GetCompanyAccountingV2Response
from pay_fit_python_sdk import configuration


class TestGetCompanyAccountingV2Response(unittest.TestCase):
    """GetCompanyAccountingV2Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
