# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import pay_fit_python_sdk
from pay_fit_python_sdk.model.payroll_status import PayrollStatus
from pay_fit_python_sdk import configuration


class TestPayrollStatus(unittest.TestCase):
    """PayrollStatus unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
