# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AccountingV2(BaseModel):
    # Date of accounting operation.
    operation_date: date = Field(alias='operationDate')

    # The analyticCode allows to group operation by label.
    analytic_code: typing.Optional[str] = Field(alias='analyticCode')

    # The fullname of the concerned employee.
    employee_full_name: str = Field(alias='employeeFullName')

    # Refers to an account's unique numerical identifier in an accounting system.
    account_id: str = Field(alias='accountId')

    # Represents the textual description of the account.
    account_name: str = Field(alias='accountName')

    # Amount of the debit operation.
    debit: typing.Optional[typing.Union[int, float]] = Field(alias='debit')

    # Amount of the credit operation.
    credit: typing.Optional[typing.Union[int, float]] = Field(alias='credit')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
