# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_fit_python_sdk.pydantic.collaborator_list_meal_vouchers_response_meal_vouchers import CollaboratorListMealVouchersResponseMealVouchers
from pay_fit_python_sdk.pydantic.collaborator_list_meal_vouchers_response_meta import CollaboratorListMealVouchersResponseMeta

class CollaboratorListMealVouchersResponse(BaseModel):
    meal_vouchers: CollaboratorListMealVouchersResponseMealVouchers = Field(alias='mealVouchers')

    meta: CollaboratorListMealVouchersResponseMeta = Field(alias='meta')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
