# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CollaboratorListPayslipsResponsePayslipsItem(BaseModel):
    # The year of the payslip
    year: str = Field(alias='year')

    # The month of the payslip. \"01\" being January and \"12\" December
    month: str = Field(alias='month')

    # Contract to which the payslip is associated
    contract_id: str = Field(alias='contractId')

    # Id of the payslip
    payslip_id: str = Field(alias='payslipId')

    # Url on the Payfit API to retrieve the payslip file
    payslip_url: str = Field(alias='payslipUrl')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
