# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TimeInformation(BaseModel):
    # Weekly hours defined in the contract. It will be available if `contracts:time-information:read` scope is set on the token.
    standard_weekly_hours: typing.Optional[typing.Union[int, float]] = Field(alias='standardWeeklyHours')

    # Percentage of weekly hours in the contract. It will be available if `contracts:time-information:read` scope is set on the token.
    full_time_equivalent: typing.Optional[typing.Union[int, float]] = Field(alias='fullTimeEquivalent')

    # Will be set to `true` if `fullTimeEquivalent` is at 1. It will be available if `contracts:time-information:read` scope is set on the token.
    is_full_time: typing.Optional[bool] = Field(alias='isFullTime')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
