# coding: utf-8

# flake8: noqa

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from pay_fit_python_sdk.api_client import ApiClient

# import Configuration
from pay_fit_python_sdk.configuration import Configuration

# import exceptions
from pay_fit_python_sdk.exceptions import OpenApiException
from pay_fit_python_sdk.exceptions import ApiAttributeError
from pay_fit_python_sdk.exceptions import ApiTypeError
from pay_fit_python_sdk.exceptions import ApiValueError
from pay_fit_python_sdk.exceptions import ApiKeyError
from pay_fit_python_sdk.exceptions import ApiException

from pay_fit_python_sdk.client import PayFit
