# coding: utf-8
"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from pay_fit_python_sdk.client_custom import ClientCustom
from pay_fit_python_sdk.configuration import Configuration
from pay_fit_python_sdk.api_client import ApiClient
from pay_fit_python_sdk.type_util import copy_signature
from pay_fit_python_sdk.apis.tags.collaborator_api import CollaboratorApi
from pay_fit_python_sdk.apis.tags.company_api import CompanyApi
from pay_fit_python_sdk.apis.tags.contract_api import ContractApi



class PayFit(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.collaborator: CollaboratorApi = CollaboratorApi(api_client)
        self.company: CompanyApi = CompanyApi(api_client)
        self.contract: ContractApi = ContractApi(api_client)
