# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCollaboratorListPayslipsResponsePayslipsItem(TypedDict):
    # The year of the payslip
    year: str

    # The month of the payslip. \"01\" being January and \"12\" December
    month: str

    # Contract to which the payslip is associated
    contractId: str

    # Id of the payslip
    payslipId: str

    # Url on the Payfit API to retrieve the payslip file
    payslipUrl: str

class OptionalCollaboratorListPayslipsResponsePayslipsItem(TypedDict, total=False):
    pass

class CollaboratorListPayslipsResponsePayslipsItem(RequiredCollaboratorListPayslipsResponsePayslipsItem, OptionalCollaboratorListPayslipsResponsePayslipsItem):
    pass
