# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCollaboratorContract(TypedDict):
    # Id of the contract.
    id: str

    # Start date of a contract in the format YYYY-MM-DD.
    startDate: typing.Optional[date]

    # End date of a contract in the format YYYY-MM-DD.
    endDate: typing.Optional[date]

    # The status of the contract.
    status: str

class OptionalCollaboratorContract(TypedDict, total=False):
    pass

class CollaboratorContract(RequiredCollaboratorContract, OptionalCollaboratorContract):
    pass
