# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_fit_python_sdk.type.contract_update_health_insurance_affiliation_request_health_insurance_contract_ids import ContractUpdateHealthInsuranceAffiliationRequestHealthInsuranceContractIds

class RequiredContractUpdateHealthInsuranceAffiliationRequest(TypedDict):
    healthInsuranceContractIds: ContractUpdateHealthInsuranceAffiliationRequestHealthInsuranceContractIds

class OptionalContractUpdateHealthInsuranceAffiliationRequest(TypedDict, total=False):
    pass

class ContractUpdateHealthInsuranceAffiliationRequest(RequiredContractUpdateHealthInsuranceAffiliationRequest, OptionalContractUpdateHealthInsuranceAffiliationRequest):
    pass
