# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_fit_python_sdk.type.contract_list_worked_time_by_pay_period_response_contracts import ContractListWorkedTimeByPayPeriodResponseContracts
from pay_fit_python_sdk.type.contract_list_worked_time_by_pay_period_response_meta import ContractListWorkedTimeByPayPeriodResponseMeta

class RequiredContractListWorkedTimeByPayPeriodResponse(TypedDict):
    contracts: ContractListWorkedTimeByPayPeriodResponseContracts

    meta: ContractListWorkedTimeByPayPeriodResponseMeta

class OptionalContractListWorkedTimeByPayPeriodResponse(TypedDict, total=False):
    pass

class ContractListWorkedTimeByPayPeriodResponse(RequiredContractListWorkedTimeByPayPeriodResponse, OptionalContractListWorkedTimeByPayPeriodResponse):
    pass
