# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_fit_python_sdk.type.contract_list_french_contracts_response_contracts import ContractListFrenchContractsResponseContracts
from pay_fit_python_sdk.type.contract_list_french_contracts_response_meta import ContractListFrenchContractsResponseMeta

class RequiredContractListFrenchContractsResponse(TypedDict):
    pass

class OptionalContractListFrenchContractsResponse(TypedDict, total=False):
    contracts: ContractListFrenchContractsResponseContracts

    meta: ContractListFrenchContractsResponseMeta

class ContractListFrenchContractsResponse(RequiredContractListFrenchContractsResponse, OptionalContractListFrenchContractsResponse):
    pass
