# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGetCollaboratorsResponseCollaboratorsItemAddressesItem(TypedDict):
    # Address of the collaborator containing the streetNumber, streetType and streetName.
    address: str

    # Postcode of the collaborator's address.
    postcode: str

    # City of the collaborator's address.
    city: str

    # Type of the address.
    type: str

class OptionalGetCollaboratorsResponseCollaboratorsItemAddressesItem(TypedDict, total=False):
    # Country of the collaborator's address.
    country: str

class GetCollaboratorsResponseCollaboratorsItemAddressesItem(RequiredGetCollaboratorsResponseCollaboratorsItemAddressesItem, OptionalGetCollaboratorsResponseCollaboratorsItemAddressesItem):
    pass
