# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_fit_python_sdk.type.get_provident_fund_contracts_response_contracts_item_affiliated_contract_ids import GetProvidentFundContractsResponseContractsItemAffiliatedContractIds

class RequiredGetProvidentFundContractsResponseContractsItem(TypedDict):
    # The generated PayFit id of the contract
    idContrat: str

    # The reference of the contract
    refContrat: typing.Optional[str]

    codePopulation: typing.Optional[str]

    codeOption: typing.Optional[str]

    affiliatedContractIds: GetProvidentFundContractsResponseContractsItemAffiliatedContractIds

    # The computation type of the provident fund contribution contract (1: Rate; 2: Fixed amount; 3: Rate and fixed amount)
    modeCalculCotisation: typing.Optional[str]

    # The contribution base (1: Tiers; 2: Gross salary; 3: Tiers and gross salary; 4: PMSS; 5: Tiers, gross salary, and PMSS)
    baseDeCotisation: typing.Optional[str]

class OptionalGetProvidentFundContractsResponseContractsItem(TypedDict, total=False):
    pass

class GetProvidentFundContractsResponseContractsItem(RequiredGetProvidentFundContractsResponseContractsItem, OptionalGetProvidentFundContractsResponseContractsItem):
    pass
