# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from pay_fit_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from pay_fit_python_sdk.api_response import AsyncGeneratorResponse
from pay_fit_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_fit_python_sdk import schemas  # noqa: F401

from pay_fit_python_sdk.model.get_provident_fund_contracts403_response import GetProvidentFundContracts403Response as GetProvidentFundContracts403ResponseSchema
from pay_fit_python_sdk.model.get_provident_fund_contracts_response import GetProvidentFundContractsResponse as GetProvidentFundContractsResponseSchema
from pay_fit_python_sdk.model.get_provident_fund_contracts404_response import GetProvidentFundContracts404Response as GetProvidentFundContracts404ResponseSchema
from pay_fit_python_sdk.model.get_provident_fund_contracts401_response import GetProvidentFundContracts401Response as GetProvidentFundContracts401ResponseSchema
from pay_fit_python_sdk.model.get_provident_fund_contracts400_response import GetProvidentFundContracts400Response as GetProvidentFundContracts400ResponseSchema

from pay_fit_python_sdk.type.get_provident_fund_contracts401_response import GetProvidentFundContracts401Response
from pay_fit_python_sdk.type.get_provident_fund_contracts404_response import GetProvidentFundContracts404Response
from pay_fit_python_sdk.type.get_provident_fund_contracts403_response import GetProvidentFundContracts403Response
from pay_fit_python_sdk.type.get_provident_fund_contracts400_response import GetProvidentFundContracts400Response
from pay_fit_python_sdk.type.get_provident_fund_contracts_response import GetProvidentFundContractsResponse

from ...api_client import Dictionary
from pay_fit_python_sdk.pydantic.get_provident_fund_contracts401_response import GetProvidentFundContracts401Response as GetProvidentFundContracts401ResponsePydantic
from pay_fit_python_sdk.pydantic.get_provident_fund_contracts_response import GetProvidentFundContractsResponse as GetProvidentFundContractsResponsePydantic
from pay_fit_python_sdk.pydantic.get_provident_fund_contracts400_response import GetProvidentFundContracts400Response as GetProvidentFundContracts400ResponsePydantic
from pay_fit_python_sdk.pydantic.get_provident_fund_contracts403_response import GetProvidentFundContracts403Response as GetProvidentFundContracts403ResponsePydantic
from pay_fit_python_sdk.pydantic.get_provident_fund_contracts404_response import GetProvidentFundContracts404Response as GetProvidentFundContracts404ResponsePydantic

from . import path

# Path params
CompanyIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyId': typing.Union[CompanyIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_id = api_client.PathParameter(
    name="companyId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyIdSchema,
    required=True,
)
_auth = [
    'partner-api-oauth',
]
SchemaFor200ResponseBodyApplicationJson = GetProvidentFundContractsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: GetProvidentFundContractsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: GetProvidentFundContractsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = GetProvidentFundContracts400ResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: GetProvidentFundContracts400Response


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: GetProvidentFundContracts400Response


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = GetProvidentFundContracts401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: GetProvidentFundContracts401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: GetProvidentFundContracts401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = GetProvidentFundContracts403ResponseSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: GetProvidentFundContracts403Response


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: GetProvidentFundContracts403Response


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = GetProvidentFundContracts404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: GetProvidentFundContracts404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: GetProvidentFundContracts404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '401': _response_for_401,
    '403': _response_for_403,
    '404': _response_for_404,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _provident_fund_contracts_mapped_args(
        self,
        company_id: str,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        if company_id is not None:
            _path_params["companyId"] = company_id
        args.path = _path_params
        return args

    async def _aprovident_fund_contracts_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List all Provident Fund contracts
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/provident-fund-contracts',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _provident_fund_contracts_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List all Provident Fund contracts
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/provident-fund-contracts',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ProvidentFundContractsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aprovident_fund_contracts(
        self,
        company_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._provident_fund_contracts_mapped_args(
            company_id=company_id,
        )
        return await self._aprovident_fund_contracts_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def provident_fund_contracts(
        self,
        company_id: str,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._provident_fund_contracts_mapped_args(
            company_id=company_id,
        )
        return self._provident_fund_contracts_oapg(
            path_params=args.path,
        )

class ProvidentFundContracts(BaseApi):

    async def aprovident_fund_contracts(
        self,
        company_id: str,
        validate: bool = False,
        **kwargs,
    ) -> GetProvidentFundContractsResponsePydantic:
        raw_response = await self.raw.aprovident_fund_contracts(
            company_id=company_id,
            **kwargs,
        )
        if validate:
            return GetProvidentFundContractsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(GetProvidentFundContractsResponsePydantic, raw_response.body)
    
    
    def provident_fund_contracts(
        self,
        company_id: str,
        validate: bool = False,
    ) -> GetProvidentFundContractsResponsePydantic:
        raw_response = self.raw.provident_fund_contracts(
            company_id=company_id,
        )
        if validate:
            return GetProvidentFundContractsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(GetProvidentFundContractsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        company_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._provident_fund_contracts_mapped_args(
            company_id=company_id,
        )
        return await self._aprovident_fund_contracts_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        company_id: str,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._provident_fund_contracts_mapped_args(
            company_id=company_id,
        )
        return self._provident_fund_contracts_oapg(
            path_params=args.path,
        )

