# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id_collaborators.get import CollaboratorsRaw
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id.get import GetByIdRaw
from pay_fit_python_sdk.paths.companies_company_id_collaborators_meal_vouchers.get import ListMealVouchersRaw
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id_payslips.get import ListPayslipsRaw
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id_contracts_contract_id_payslips_payslip_id.get import ViewPayslipRaw


class CollaboratorApiRaw(
    CollaboratorsRaw,
    GetByIdRaw,
    ListMealVouchersRaw,
    ListPayslipsRaw,
    ViewPayslipRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
