# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id_collaborators.get import Collaborators
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id.get import GetById
from pay_fit_python_sdk.paths.companies_company_id_collaborators_meal_vouchers.get import ListMealVouchers
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id_payslips.get import ListPayslips
from pay_fit_python_sdk.paths.companies_company_id_collaborators_collaborator_id_contracts_contract_id_payslips_payslip_id.get import ViewPayslip
from pay_fit_python_sdk.apis.tags.collaborator_api_raw import CollaboratorApiRaw


class CollaboratorApi(
    Collaborators,
    GetById,
    ListMealVouchers,
    ListPayslips,
    ViewPayslip,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CollaboratorApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CollaboratorApiRaw(api_client)
