# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id.get import Company
from pay_fit_python_sdk.paths.companies_company_id_accounting.get import CompanyAccounting
from pay_fit_python_sdk.paths.companies_company_id_accounting_v2.get import CompanyAccountingV2
from pay_fit_python_sdk.paths.companies_company_id_payroll_status.get import CompanyPayrollStatus
from pay_fit_python_sdk.paths.companies_fr_company_id.get import GetBasicInfoFr
from pay_fit_python_sdk.paths.companies_company_id_health_insurance_contracts.get import HealthInsuranceContracts
from pay_fit_python_sdk.paths.companies_company_id_provident_fund_contracts.get import ProvidentFundContracts
from pay_fit_python_sdk.apis.tags.company_api_raw import CompanyApiRaw


class CompanyApi(
    Company,
    CompanyAccounting,
    CompanyAccountingV2,
    CompanyPayrollStatus,
    GetBasicInfoFr,
    HealthInsuranceContracts,
    ProvidentFundContracts,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CompanyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CompanyApiRaw(api_client)
