# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id.get import CompanyRaw
from pay_fit_python_sdk.paths.companies_company_id_accounting.get import CompanyAccountingRaw
from pay_fit_python_sdk.paths.companies_company_id_accounting_v2.get import CompanyAccountingV2Raw
from pay_fit_python_sdk.paths.companies_company_id_payroll_status.get import CompanyPayrollStatusRaw
from pay_fit_python_sdk.paths.companies_fr_company_id.get import GetBasicInfoFrRaw
from pay_fit_python_sdk.paths.companies_company_id_health_insurance_contracts.get import HealthInsuranceContractsRaw
from pay_fit_python_sdk.paths.companies_company_id_provident_fund_contracts.get import ProvidentFundContractsRaw


class CompanyApiRaw(
    CompanyRaw,
    CompanyAccountingRaw,
    CompanyAccountingV2Raw,
    CompanyPayrollStatusRaw,
    GetBasicInfoFrRaw,
    HealthInsuranceContractsRaw,
    ProvidentFundContractsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
