# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id_contracts_contract_id.get import ContractRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts.get import ContractsRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id.get import GetFrenchInfoRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr.get import ListFrenchContractsRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts_time.get import ListWorkedTimeByPayPeriodRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id_health_insurance.put import UpdateHealthInsuranceAffiliationRaw
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id_provident_fund.put import UpdateProvidentFundAffiliationRaw


class ContractApiRaw(
    ContractRaw,
    ContractsRaw,
    GetFrenchInfoRaw,
    ListFrenchContractsRaw,
    ListWorkedTimeByPayPeriodRaw,
    UpdateHealthInsuranceAffiliationRaw,
    UpdateProvidentFundAffiliationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
