# coding: utf-8

"""
    Partner API

    A Semi-Private API to let third parties communicate with PayFit

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from pay_fit_python_sdk.paths.companies_company_id_contracts_contract_id.get import Contract
from pay_fit_python_sdk.paths.companies_company_id_contracts.get import Contracts
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id.get import GetFrenchInfo
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr.get import ListFrenchContracts
from pay_fit_python_sdk.paths.companies_company_id_contracts_time.get import ListWorkedTimeByPayPeriod
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id_health_insurance.put import UpdateHealthInsuranceAffiliation
from pay_fit_python_sdk.paths.companies_company_id_contracts_fr_contract_id_provident_fund.put import UpdateProvidentFundAffiliation
from pay_fit_python_sdk.apis.tags.contract_api_raw import ContractApiRaw


class ContractApi(
    Contract,
    Contracts,
    GetFrenchInfo,
    ListFrenchContracts,
    ListWorkedTimeByPayPeriod,
    UpdateHealthInsuranceAffiliation,
    UpdateProvidentFundAffiliation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ContractApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ContractApiRaw(api_client)
